# Route 1: City of Imus to Indang, Cavite (Vice-Versa)
starting_place_1 = [
    'Indang',
    'Cuso',
    'Kaytapos',
    'Petron Alulod',
    'Alulod',
    'Metrogate',
    'M. Lupa/Brgy. Hall',
    'Checkpoint',
    'Regina',
    'Sampaguita',
    'Kodi',
    'Trece Martires City',
    'Concho',
    'Perez',
    'Metro South',
    'Metropolis',
    'Tinongan',
    'Manggahan',
    'Stateland',
    'Monterey',
    'FCIE-Langkaan',
    'Slaughter',
    'Pala-Pala',
    'San Agustin',
    'Dasmariñas',
    'Bauman',
    'Arcontica',
    'Salitran',
    'San Miguel',
    'Coastal Anabu',
    'Yazaki',
    'Doyets',
    'CBI',
    'Patindig Araw',
    'Robinson',
    'Pac Mac',
    'Imus Toll Dr.',
    'LTO',
    'SM Bacoor'
]